build:
  image: docker:19.03.1
  only:
    - tags
  stage: build
  services:
    - docker:19.03.1-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - IMAGE_TAG=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
